### ISSUE TITLE
How can I find Railway API ??

### ISSUE THREAD

**Issue by Kistlak** [chathurabuddi/RailLanka#1]
I tried with ICTA link that you provided. But , that link is not working now. Then how can I find Sri Lanka Railway Schedule API ?? Please give me a reply. 

Thank You,
Kistlak.

**Comment by chathurabuddi** [comment]
API was updated to newer version. Now you have to obtain a access key to access the current API. Contact developers and explain your requriments. They will provide you access token and API documentation.
